name: Full Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        dotnet-quality: 'preview'
    - name: Install SQL Local DB
      run: ./setup-sqllocaldb.ps1
      shell: pwsh
    - name: Build
      run: dotnet build QuerySpecification.sln --configuration Release
    - name: Test
      run: dotnet test QuerySpecification.sln --configuration Release --no-build --no-restore --collect:"xplat code coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
      with:
        reports: 'tests/**/coverage.cobertura.xml'
        targetdir: 'TestResults'
        # reporttypes: MarkdownSummary
        assemblyfilters: '-*Tests*;'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: TestResults
    # - name: Publish coverage in build summary
      # run: cat TestResults/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      # shell: bash
