name: Full Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        dotnet-quality: 'preview'
    - name: Install SQL Local DB
      run: ./setup-sqllocaldb.ps1
      shell: pwsh
    - name: Build
      run: dotnet build QuerySpecification.sln --configuration Release
    - name: Test
      run: dotnet test QuerySpecification.sln --configuration Release --no-build --no-restore --collect:"xplat code coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
      with:
        reports: 'tests/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'Html;Badges'
        assemblyfilters: '-*Tests*'
    - name: Update Gist with SVG using gh
      run: gh gist edit $env:GIST_ID --add coveragereport/badge_combined.svg --filename badge_combined.svg
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}

