name: Full Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        dotnet-quality: 'preview'
    - name: Install SQL Local DB
      run: ./setup-sqllocaldb.ps1
      shell: pwsh
    - name: Build
      run: dotnet build QuerySpecification.sln --configuration Release
    - name: Test
      run: dotnet test QuerySpecification.sln --configuration Release --no-build --no-restore --collect:"XPlat Code Coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
      with:
        reports: 'tests/**/coverage.cobertura.xml'
        targetdir: '${{ runner.temp }}/coveragereport'
        reporttypes: 'Html;Badges;MarkdownSummaryGithub'
        assemblyfilters: '-*Tests*'
    - name: Publish coverage report in build summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Update Gist with coverage report
      run: |
        gh gist edit $env:GIST_ID --add coveragereport/badge_combined.svg --filename badge_combined.svg
        gh gist edit $env:GIST_ID --add coveragereport/SummaryGithub.md --filename SummaryGithub.md
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
    # - name: Copy report to a temp directory
    #   run: cp -rp coveragereport ${{ runner.temp }}/
    - name: Create coverage-reports branch and push content
      run: |
        git fetch
        git checkout coverage-reports || git checkout --orphan coverage-reports
        rm -rf ./*
        cp -rp ${{ runner.temp }}/coveragereport/* ./
        git add .
        git commit -m "Update coverage reports [skip ci]" || echo "No changes to commit"
        git push origin coverage-reports --force
      shell: bash
